### ISSUE TITLE
Tips to make it work (by author)

### ISSUE THREAD

**Issue by hongyi-zhang** [moskomule/mixup.pytorch#1]
Hi, here's a few tips for applying mixup:
1. Whenever possible, use a network with large capacity (i.e. one that severely overfits the training data)
2. Otherwise (say in your case of ResNet-20), reduce alpha. Try alpha = 0.2 or 0.4, for example, to reduce underfitting.

**Comment by moskomule** [comment]
Hi!, I was excited to read your paper but wondered why it doesn't work well. 

Thank you for your advice. I'll try and update the result!

**Comment by moskomule** [comment]
@hongyi-zhang I tried alpha 0.1, 0.2 and 0.4  then yes, as you say, the accuracies increased a bit. Thank you.
